# Generated by Django 2.1.2 on 2019-01-08 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='动作名')),
                ('action', models.CharField(max_length=50, verbose_name='具体动作')),
            ],
            options={
                'verbose_name': '动作表',
                'verbose_name_plural': '动作表',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='菜单名')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.Menu')),
            ],
            options={
                'verbose_name': '菜单表',
                'verbose_name_plural': '菜单表',
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='权限名称')),
                ('url', models.CharField(max_length=200, verbose_name='权限URL')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.Menu')),
            ],
            options={
                'verbose_name': '权限表',
                'verbose_name_plural': '权限表',
            },
        ),
        migrations.CreateModel(
            name='PermissionAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.Action', verbose_name='动作')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.Permission', verbose_name='权限')),
            ],
            options={
                'verbose_name': '权限动作中间表',
                'verbose_name_plural': '权限动作中间表',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='角色名称')),
            ],
            options={
                'verbose_name': '角色表',
                'verbose_name_plural': '角色表',
            },
        ),
        migrations.CreateModel(
            name='RolePermissionAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.PermissionAction')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.Role')),
            ],
            options={
                'verbose_name': '角色和权限动作中间表',
                'verbose_name_plural': '角色和权限动作中间表',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='用户名')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
            ],
            options={
                'verbose_name': '用户表',
                'verbose_name_plural': '用户表',
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.Role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.User')),
            ],
            options={
                'verbose_name': '用户和角色之间的中间表',
                'verbose_name_plural': '用户和角色之间的中间表',
            },
        ),
    ]
